root = "0x5bfab3b16c0b81bc3107fac869261418818ac0fe03745cd486350dcc8929a321"

[high_certificate.Qc]
signatures = "0xf865c20101b8608dba397e246729b17c283d4dc031ebd9ded1b46e2cd2d4deed2ca32984b63d2f58535219ccb5d7e0b95c2e6aa34d1da801a3258f49827cfae648fba4a6d42eb8876edb5c0d321f462e0ed8ece4df71136146edde6a0230d8fd4e1450af342e50"

[high_certificate.Qc.info]
id = "0x288f5f30a836df2f9652c836727f76853b8b42d3c6a1baac79daad1b5df00ff5"
round = 63
epoch = 1

[[validator_sets]]
epoch = 1
round = 0
