#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

#########################################################
# Node-specific configuration
#########################################################
beneficiary = "0x0000000000000000000000000000000000000000"
node_name = "dev-node"
network_name = "devnet"
ipc_tx_batch_size = 5000
ipc_max_queued_batches = 6
# must be <= ipc_max_queued_batches
ipc_queued_batches_watermark = 3

statesync_threshold = 600
statesync_max_concurrent_requests = 5

#########################################################
# Network-wide configuration
#########################################################
chain_id = 20143

#########################################################
# Node-specific configuration
#########################################################
[bootstrap]
peers = []
# [[bootstrap.peers]]
# address = "192.168.2.106:8000"
# record_seq_num = 0
# secp256k1_pubkey = "0x02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5"
# name_record_sig = "6a332aff5406ecd3ebe8f69153d1cb83393af8edcd2482b40e282b87949304af546c5bcdb507e84e20a2165f45917cce309d21a7b0b44f01fa143922bed056a401"

[peer_discovery]
self_address = "0.0.0.0:8000"
self_record_seq_num = 0
# self_name_record_sig = "c98647175522973cc67e5851a0a3ab472a6b7b11f93fe3a1db38fe7d086f3aa3466b5bd2b13b8996d9593e1d3cf07682d366441b5cd1d4db63f049e351e649b300"
self_name_record_sig = "85663053b3d719985357b56270ba320abadd1c51e10ea06430f3990d81393dc7770ff661c331bd631afca705029b0fd77cc0f48d46b37c8d8523c73c6af1242801"
refresh_period = 120
request_timeout = 5
unresponsive_prune_threshold = 5
last_participation_prune_threshold = 5000
min_num_peers = 0
max_num_peers = 200

[fullnode_dedicated]
identities = []
# [[fullnode_dedicated.identities]]
# secp256k1_pubkey = "..."

[blocksync_override]
peers = []
# [[blocksync_override.peers]]
# secp256k1_pubkey = "..."

[statesync]
expand_to_group = true
init_peers = []
# [[statesync.init_peers]]
# secp256k1_pubkey = "..."

[fullnode_raptorcast]
enable_publisher = false
enable_client = false
raptor10_fullnode_redundancy_factor = 3.0
max_group_size = 10
round_span = 240
invite_lookahead = 120
max_invite_wait = 10
deadline_round_dist = 10
init_empty_round_span = 23
max_num_group = 3
invite_future_dist_min = 1
invite_future_dist_max = 600
invite_accept_heartbeat_ms = 10000

[fullnode_raptorcast.full_nodes_prioritized]
identities = []

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8000
max_rtt_ms = 300
max_mbps = 1000
buffer_size = 8388608  # 8MB，与系统限制匹配